### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by rybkinevg** [rinvex/attributes#172]
Hello!

I noticed that your amazing package has Laravel 9 comparability, but I am not able to install it on the fresh Laravel 9 project.

I am getting the error below:

___

$ composer require rinvex/laravel-attributes
Using version ^6.1 for rinvex/laravel-attributes
./composer.json has been updated
Running composer update rinvex/laravel-attributes
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - felixkiss/uniquewith-validator 3.4.2 requires illuminate/support ^5.5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - rinvex/laravel-support v6.1.0 requires felixkiss/uniquewith-validator dev-l9-compatibility -> found felixkiss/uniquewith-validator[dev-master, 1.0.0, ..., 1.1.4, 2.0.0, ..., 2.0.8, 3.0.0, ..., 3.4.2] but it does not match the constraint.
    - rinvex/laravel-attributes v6.1.0 requires rinvex/laravel-support ^6.0.0 -> satisfiable by rinvex/laravel-support[v6.0.0, ..., v6.1.0].
    - rinvex/laravel-support[v6.0.0, ..., v6.0.3] require felixkiss/uniquewith-validator ^3.4.2 -> satisfiable by felixkiss/uniquewith-validator[3.4.2].
    - Root composer.json requires rinvex/laravel-attributes ^6.1 -> satisfiable by rinvex/laravel-attributes[v6.1.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require rinvex/laravel-attributes:*" to figure out if any version is installable, or "composer require rinvex/laravel-attributes:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

___

Could you please advice, what I am missing ?

Thanks!

**Comment by Omranic** [comment]
Yes, that's because one of the composer dependencies is not yet compatible with Laravel v9, so you've to do one more easy step to get it working, please check this note on upgrading to Laravel v9:

https://github.com/rinvex/laravel-support#note-for-laravel-v9

## Note for Laravel v9

This package requires `felixkiss/uniquewith-validator` dependency, which is not yet compatible with Laravel v9! However as a temporary workaround, add [Laravel Shift](https://github.com/felixkiss/uniquewith-validator/pull/131)'s fork to the `repositories` property of your project root `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/uniquewith-validator.git"
        }
    ]
}
```
